/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ptsdxTT8ARM
 */
import { Button } from "@/components/ui/button"

export function testing() {
  return (
    <div className="bg-white py-16">
      <div className="container mx-auto px-4">
        <div className="flex flex-wrap items-center justify-between">
          <div className="w-full lg:w-1/2">
            <h2 className="text-3xl font-bold text-gray-900">The all-in-one solution</h2>
            <h1 className="mt-4 text-5xl font-extrabold text-gray-900">
              Enterprise SSO <span className="text-purple-600">(and a whole lot more)</span>
            </h1>
            <p className="mt-4 text-lg text-gray-600">
              WorkOS is a set of building blocks for quickly adding enterprise features to your app. You’ll be shipping
              quickly with a market-proven solution for your customers.
            </p>
            <Button className="mt-6 bg-purple-600 text-white">Add Single Sign-On to your app</Button>
          </div>
          <div className="w-full lg:w-1/2 lg:pl-10">
            <img
              alt="Enterprise SSO Illustration"
              className="mx-auto"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/400",
                objectFit: "cover",
              }}
              width="500"
            />
          </div>
        </div>
        <div className="mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="text-center">
            <LockIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Auth for all SSO providers</h3>
            <p className="mt-2 text-sm text-gray-600">
              Support any SAML or OIDC identity provider with a single integration
            </p>
          </div>
          <div className="text-center">
            <GlobeIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Social authentication</h3>
            <p className="mt-2 text-sm text-gray-600">Sign in to your app with Microsoft, Google, and more</p>
          </div>
          <div className="text-center">
            <MailIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Magic Auth</h3>
            <p className="mt-2 text-sm text-gray-600">Passwordless auth with a six-digit code sent via email</p>
          </div>
          <div className="text-center">
            <ShieldCheckIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Complete User Management</h3>
            <p className="mt-2 text-sm text-gray-600">
              Manage users and organizations, set policies, and support all auth types
            </p>
          </div>
          <div className="text-center">
            <TerminalIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">AuthKit</h3>
            <p className="mt-2 text-sm text-gray-600">Flexible authentication UI powered by WorkOS and Radix</p>
          </div>
          <div className="text-center">
            <FingerprintIcon className="mx-auto h-12 w-12 bg-gray-100 text-purple-600 p-3 rounded-lg" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Multi-Factor Auth</h3>
            <p className="mt-2 text-sm text-gray-600">
              Manage users and organizations, set policies, and support all auth types
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}


function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function ShieldCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function TerminalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" x2="20" y1="19" y2="19" />
    </svg>
  )
}


function FingerprintIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12C2 6.5 6.5 2 12 2a10 10 0 0 1 8 4" />
      <path d="M5 19.5C5.5 18 6 15 6 12c0-.7.12-1.37.34-2" />
      <path d="M17.29 21.02c.12-.6.43-2.3.5-3.02" />
      <path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4" />
      <path d="M8.65 22c.21-.66.45-1.32.57-2" />
      <path d="M14 13.12c0 2.38 0 6.38-1 8.88" />
      <path d="M2 16h.01" />
      <path d="M21.8 16c.2-2 .131-5.354 0-6" />
      <path d="M9 6.8a6 6 0 0 1 9 5.2c0 .47 0 1.17-.02 2" />
    </svg>
  )
}
